replicaCount: 2

image:
  repository: tessydocker/flask-backend
  tag: v8
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  welcomeMessage: "Hello from Backend!"

namespace: microservices
