apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.targetPort }}

        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: WELCOME_MESSAGE


        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2

        resources:
{{ toYaml .Values.resources | indent 10 }}
